export interface ThemePreset {
  name: string
  description: string
  backgroundColor: string
  textColor: string
  accentColor: string
  buttonStyle: 'solid' | 'outline' | 'rounded'
  preview: string // emoji or icon
}

export const themePresets: ThemePreset[] = [
  {
    name: 'Dark+',
    description: 'VS Code Dark+',
    backgroundColor: '#1e1e1e',
    textColor: '#d4d4d4',
    accentColor: '#007acc',
    buttonStyle: 'rounded',
    preview: '🌙',
  },
  {
    name: 'Dracula',
    description: 'Dracula theme',
    backgroundColor: '#282a36',
    textColor: '#f8f8f2',
    accentColor: '#bd93f9',
    buttonStyle: 'rounded',
    preview: '🧛',
  },
  {
    name: 'Nord',
    description: 'Nord theme',
    backgroundColor: '#2e3440',
    textColor: '#d8dee9',
    accentColor: '#88c0d0',
    buttonStyle: 'rounded',
    preview: '❄️',
  },
  {
    name: 'One Dark',
    description: 'Atom One Dark',
    backgroundColor: '#282c34',
    textColor: '#abb2bf',
    accentColor: '#61afef',
    buttonStyle: 'rounded',
    preview: '🌑',
  },
  {
    name: 'Tokyo Night',
    description: 'Tokyo Night',
    backgroundColor: '#1a1b26',
    textColor: '#c0caf5',
    accentColor: '#7aa2f7',
    buttonStyle: 'rounded',
    preview: '🌃',
  },
  {
    name: 'Material Dark',
    description: 'Material Theme Dark',
    backgroundColor: '#263238',
    textColor: '#eeffff',
    accentColor: '#82aaff',
    buttonStyle: 'rounded',
    preview: '🎨',
  },
  {
    name: 'Monokai',
    description: 'Monokai Pro',
    backgroundColor: '#272822',
    textColor: '#f8f8f2',
    accentColor: '#f92672',
    buttonStyle: 'rounded',
    preview: '🎭',
  },
  {
    name: 'Solarized Dark',
    description: 'Solarized Dark',
    backgroundColor: '#002b36',
    textColor: '#839496',
    accentColor: '#268bd2',
    buttonStyle: 'rounded',
    preview: '☀️',
  },
  {
    name: 'GitHub Dark',
    description: 'GitHub Dark',
    backgroundColor: '#0d1117',
    textColor: '#c9d1d9',
    accentColor: '#58a6ff',
    buttonStyle: 'rounded',
    preview: '🐙',
  },
  {
    name: 'Gruvbox Dark',
    description: 'Gruvbox Dark',
    backgroundColor: '#282828',
    textColor: '#ebdbb2',
    accentColor: '#fe8019',
    buttonStyle: 'rounded',
    preview: '🎨',
  },
  {
    name: 'Catppuccin',
    description: 'Catppuccin Mocha',
    backgroundColor: '#1e1e2e',
    textColor: '#cdd6f4',
    accentColor: '#89b4fa',
    buttonStyle: 'rounded',
    preview: '🐱',
  },
  {
    name: 'Ayu Dark',
    description: 'Ayu Dark',
    backgroundColor: '#0a0e14',
    textColor: '#b3b1ad',
    accentColor: '#ff8f40',
    buttonStyle: 'rounded',
    preview: '🌊',
  },
  {
    name: 'Light+',
    description: 'VS Code Light+',
    backgroundColor: '#ffffff',
    textColor: '#383a42',
    accentColor: '#007acc',
    buttonStyle: 'outline',
    preview: '☀️',
  },
  {
    name: 'GitHub Light',
    description: 'GitHub Light',
    backgroundColor: '#ffffff',
    textColor: '#24292f',
    accentColor: '#0969da',
    buttonStyle: 'outline',
    preview: '☀️',
  },
  {
    name: 'Solarized Light',
    description: 'Solarized Light',
    backgroundColor: '#fdf6e3',
    textColor: '#586e75',
    accentColor: '#268bd2',
    buttonStyle: 'outline',
    preview: '🌞',
  },
]

